# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_CustomItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomItem(object):
    def setupUi(self, CustomItem):
        CustomItem.setObjectName("CustomItem")
        CustomItem.resize(510, 188)
        self.verticalLayout = QtWidgets.QVBoxLayout(CustomItem)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_TitleName = QtWidgets.QLabel(CustomItem)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_TitleName.setFont(font)
        self.label_TitleName.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_TitleName.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_TitleName.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_TitleName.setObjectName("label_TitleName")
        self.horizontalLayout_3.addWidget(self.label_TitleName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_Num = QtWidgets.QLabel(CustomItem)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_Num.setFont(font)
        self.label_Num.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_Num.setObjectName("label_Num")
        self.horizontalLayout_3.addWidget(self.label_Num)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_MainText = QtWidgets.QLabel(CustomItem)
        self.label_MainText.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_MainText.setStyleSheet("")
        self.label_MainText.setScaledContents(True)
        self.label_MainText.setWordWrap(True)
        self.label_MainText.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_MainText.setObjectName("label_MainText")
        self.verticalLayout.addWidget(self.label_MainText)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_BookName = QtWidgets.QLabel(CustomItem)
        self.label_BookName.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_BookName.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_BookName.setObjectName("label_BookName")
        self.horizontalLayout_2.addWidget(self.label_BookName)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_Volume = QtWidgets.QLabel(CustomItem)
        self.label_Volume.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_Volume.setObjectName("label_Volume")
        self.horizontalLayout.addWidget(self.label_Volume)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_FileLabel = QtWidgets.QLabel(CustomItem)
        self.label_FileLabel.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_FileLabel.setObjectName("label_FileLabel")
        self.horizontalLayout.addWidget(self.label_FileLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.label_Pages = QtWidgets.QLabel(CustomItem)
        self.label_Pages.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_Pages.setObjectName("label_Pages")
        self.horizontalLayout.addWidget(self.label_Pages)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(CustomItem)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)

        self.retranslateUi(CustomItem)
        QtCore.QMetaObject.connectSlotsByName(CustomItem)

    def retranslateUi(self, CustomItem):
        _translate = QtCore.QCoreApplication.translate
        CustomItem.setWindowTitle(_translate("CustomItem", "Form"))
        CustomItem.setToolTip(_translate("CustomItem", "<html><head/><body><p>双击阅读</p></body></html>"))
        self.label_TitleName.setText(_translate("CustomItem", ">>>邹维琏<<<"))
        self.label_Num.setText(_translate("CustomItem", "1"))
        self.label_MainText.setText(_translate("CustomItem", "邹维琏，字德辉，江西新昌人。万历三十五年进士。授延平推官。耿介有大节。……崇祯初，起南京通政参议，就迁太仆少卿，疏陈卜相、久任、纳言、议谥、筹兵五事。五年二月擢右佥都御史，代熊文灿巡抚福建。海寇刘香乱，遣游击郑芝龙击破之。海外红夷据彭湖，挟互市，后徙台湾，渐泊厦门。维琏屡檄芝龙防遏之，不听。明年夏，芝龙剿贼福宁，红夷乘间袭陷厦门城，大掠。维琏急发兵水陆进，芝龙亦驰援，焚其三舟，官军伤亦众。寇乃泛舟大洋，转掠青港、荆屿、石湾。诸将御之铜山，连战数日，始败去。维琏在事二年，劳绩甚着。会当国者温体仁辈雅忌维琏，而闽人宦京师者腾谤于朝，竟坐是罢官。八年春，叙却贼功，诏许起用。旋召拜兵部右侍郎，遘疾不赴，卒于家。……"))
        self.label_BookName.setText(_translate("CustomItem", "《明史》"))
        self.label_Volume.setText(_translate("CustomItem", "23册"))
        self.label_FileLabel.setText(_translate("CustomItem", "卷二百三十五 列传第一百二十三"))
        self.label_Pages.setText(_translate("CustomItem", "页码：6137-6138"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CustomItem = QtWidgets.QWidget()
    ui = Ui_CustomItem()
    ui.setupUi(CustomItem)
    CustomItem.show()
    sys.exit(app.exec_())
