# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_DBTreeWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DBTreeView(object):
    def setupUi(self, DBTreeView):
        DBTreeView.setObjectName("DBTreeView")
        DBTreeView.resize(439, 343)
        self.horizontalLayout = QtWidgets.QHBoxLayout(DBTreeView)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tree = QtWidgets.QTreeWidget(DBTreeView)
        self.tree.setColumnCount(2)
        self.tree.setObjectName("tree")
        self.tree.header().setVisible(False)
        self.tree.header().setCascadingSectionResizes(False)
        self.tree.header().setMinimumSectionSize(30)
        self.horizontalLayout.addWidget(self.tree)
        self.DBLayout = QtWidgets.QVBoxLayout()
        self.DBLayout.setObjectName("DBLayout")
        self.horizontalLayout.addLayout(self.DBLayout)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 8)

        self.retranslateUi(DBTreeView)
        QtCore.QMetaObject.connectSlotsByName(DBTreeView)

    def retranslateUi(self, DBTreeView):
        _translate = QtCore.QCoreApplication.translate
        DBTreeView.setWindowTitle(_translate("DBTreeView", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DBTreeView = QtWidgets.QWidget()
    ui = Ui_DBTreeView()
    ui.setupUi(DBTreeView)
    DBTreeView.show()
    sys.exit(app.exec_())
